v1/interview/urls.py
from django.urls import path
from . import views

app_name = 'interview'
urlpatterns = [
    path("setup", views.setup_page, name="setup_page"),
    path("interview/<int:interview_id>/question_index<int:question_index>/", views.interview_question_page,
         name="interview_question_page"),
    path("hint/<str:question_type>/", views.hint_page, name="hint_page"),
    path("summary", views.interview_summary, name="summary"),
    path("landingpage", views.landing_page, name="landing_page"),
    path("", views.landing_page, name="landing_page"),
    path("test/", views.test, name="test"),
    path("upload_voice/", views.upload_voice, name="upload_voice"),

    path("career_background", views.career_background, name="career_background"),
    path("career_interests", views.career_interests, name="career_interests"),
    path("career_intro", views.career_intro, name="career_intro"),
    path("career_preferences", views.career_preferences, name="career_preferences"),
    path("career_results", views.career_results, name="career_results"),
    path("career_chat", views.career_chat, name="career_chat"),
    path("career_personality", views.career_personality, name="career_personality"),
    path("track_intro", views.track_intro, name="track_intro"),

    path('register', views.user_register, name='register'),
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),

    path('dashboard', views.dashboard, name='dashboard'),
    # path('interview_list', views.interview_list, name='interview_list'),
    # path('interview_questions/<str:interview_id>/', views.questions_list_in_interview, name='questions_list_in_interview'),
    path('dashboard_main', views.dashboard_main, name='dashboard_main'),
    path('dashboard_interview/<str:interview_id>/', views.dashboard_interview, name='dashboard_interview'),
    path('single_question/<str:question_id>/<str:question_type>/', views.single_question_practice, name='single_question_practice'),

]

v1/interview_django_v2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('interview.urls')),
]

v1/interview/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.

# interview question
class Question(models.Model):
    question_id = models.AutoField(primary_key=True)
    QUESTION_ROLE_CHOICE = (
        ('IC', 'IC'),
        ('Manager', 'Manager'),
    )
    question_role = models.CharField(
        choices=QUESTION_ROLE_CHOICE,
        default='IC',
        max_length=20,
    )
    question_text = models.CharField(max_length=200)

    QUESTION_TYPE_CHOICE = (
        ('top10', 'top10'),
        ('communication', 'communication'),
        ('decision_making', 'decision_making'),
        ('teamwork', 'teamwork'),
        ('leadership', 'leadership'),
    )
    question_type = models.CharField(
        choices=QUESTION_TYPE_CHOICE,
        default='communication',
        max_length=20,
    )


# User
# class User(models.Model):
#     user_id = models.AutoField(primary_key=True)
#     # mail
#     # name
#     pass


# interview info table
class InterviewInfo(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, default="test")
    interview_id = models.AutoField(primary_key=True)
    total_question = models.IntegerField(default=1)
    year_of_experience = models.IntegerField(default=0)
    ROLE_CHOICE = [
        ('IC', 'IC'),
        ('Manager', 'Manager'),
    ]
    role = models.CharField(choices=ROLE_CHOICE, max_length=20)
    INTERVIEW_TYPE_CHOICE = [
        ('top10', 'top10'),
        ('communication', 'communication'),
        ('decision_making', 'decision_making'),
        ('teamwork', 'teamwork'),
        ('leadership', 'leadership'),
    ]
    interview_type = models.CharField(
        choices=INTERVIEW_TYPE_CHOICE,
        default='communication',
        max_length=20,
    )
    total_time = models.IntegerField(default=0)  # unit second
    timestamp = models.DateTimeField(default=timezone.now)


# interview question
class InterviewQuestion(models.Model):
    interview_id = models.ForeignKey(InterviewInfo, on_delete=models.CASCADE)
    question_id = models.ForeignKey(Question, on_delete=models.CASCADE)
    question_index = models.IntegerField(default=1)
    user_answer = models.CharField(max_length=2000)
    access_answer = models.CharField(max_length=2000)
    revise_answer = models.CharField(max_length=2000)

    language_score = models.IntegerField(default=1)
    vocal_score = models.IntegerField(default=1)
    content_score = models.IntegerField(default=1)

v1/interview/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
    # email = forms.EmailField(required=True)
    access_code = forms.CharField(label="Access code")

    class Meta:
        model = User
        # fields = ("username", "email", "password1", "password2")
        fields = ("username", "password1", "password2", "access_code")
        labels = {
            "username": "Email",
        }

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        # user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class CustomAuthenticationForm(AuthenticationForm):
    username = UsernameField(
        label='Email',
        widget=forms.TextInput(attrs={'autofocus': True})
    )

v1/interview/templates/interview/anchor_test.html
<!DOCTYPE html>
<html>
<head>
    <title>My Web Page</title>
</head>
<body>
    <h1>Welcome to My Web Page</h1>

    <p><a href="#section1">Go to Section 1</a></p>
    <p><a href="#section2">Go to Section 2</a></p>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div id="section1">Section 1</div>
    <p>This is the content of section 1.</p>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div id="section2">Section 2</div>
    <p>This is the content of section 2.</p>
</body>
<script>
    const menuItems = document.querySelectorAll('.menu-item');
    const contentSections = document.querySelectorAll('.content-section');

    function updateActiveMenuItem() {
        console.log("scrolling");
        contentSections.forEach((section, index) => {
            const rect = section.getBoundingClientRect();
            if (rect.top <= 200 && rect.bottom >= 200) {
                menuItems.forEach(item => item.classList.remove('active'));
                menuItems[index].classList.add('active');
            }
        });
    }

    // Event listener for scrolling
    window.addEventListener('scroll', updateActiveMenuItem);


    // Event listeners for menu items to scroll to the respective sections
    menuItems.forEach((menuItem, index) => {
        menuItem.addEventListener('click', () => {
            contentSections[index].scrollIntoView({behavior: 'smooth'});
        });
    });
</script>
</html>

v1/interview/templates/interview/career-builder-background.html
{% extends 'interview/nav.html' %}

{% block header %}
<head>
    {% load static %}
    <meta charset="utf-8">
    <title>Career Path Builder - Background</title>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link rel="stylesheet" type="text/css" href="{% static 'interview/css/career-builder-background.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'interview/css/nav.css' %}">
    <style>
        body {
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
        }
    </style>
    <script src="https://kit.fontawesome.com/1a12d6fc49.js" crossorigin="anonymous"></script>
</head>

{% endblock %}

{% block content %}

<main>
    <section id="sideNavContainer">
        <p id="sidemenu-background"><i class="fa-regular fa-circle-check" id="first-icon"></i>Background</p>
        <p id="sidemenu-interests"><i class="fa-regular fa-circle-check" id="second-icon"></i>Interests</p>
        <p id="sidemenu-preferences"><i class="fa-regular fa-circle-check" id="third-icon"></i>Preferences</p>
        <p id="sidemenu-personality"><i class="fa-regular fa-circle-check" id="forth-icon"></i>Personality</p>
    </section>

    <section id="mainContent">
        <div id="tell-us-about-yourself-container">
            <div class="theBrownVerticalDecoBar">
                <div id="tell-us-about-yourself">Tell us about yourself, we will gather your information and provide
                    career
                    track recommendations based
                    on your answer.
                </div>
            </div>
        </div>

        <h1 id="title-background">Background</h1>

        <div id="uploadResume" class="transparentContainerBox">
            <p class="second-title" id="upload-resume">Upload Your Resume</p>
            <div id="container-1">
                <div id="container-2">
                    <input type="file" id="fileInput" accept=".pdf, .doc, .docx">
                </div>
                <div id="container-3">
                    <button id="upload-button" class="submit-button">
                        <span>Upload</span>
                        <i class="fa-regular fa-circle-check" id="upload-icon"></i>
                    </button>
                </div>
                <div id="container-4">
                    <a href="{% url 'interview:career_interests' %}" id="next-button-one" class="submit-button">Next<i
                            class="fa-regular fa-circle-right"></i></a>

                </div>
            </div>
        </div>

        <script>
            // Get a collection of elements with the class "option-button"
            const buttons = document.getElementById("upload-button");
            const icon = document.getElementById("upload-icon");
            // Loop through each button and add a click event listener

            buttons.addEventListener("click", function () {
                // Add a class to change the style after it's clicked
                icon.style.display = "block";
            });
        </script>


        <script>
            document.addEventListener("DOMContentLoaded", function () {
                const fileInput = document.getElementById("fileInput");
                const uploadButton = document.getElementById("upload-button");
                const statusMessage = document.getElementById("statusMessage");

                uploadButton.addEventListener("click", function () {
                    const selectedFile = fileInput.files[0]; // Get the selected file
                    if (selectedFile) {
                        // Display a message with the file name
                        statusMessage.textContent = `Uploaded: ${selectedFile.name}`;

                        // You can perform further actions here, such as sending the file to a server using AJAX or fetching it in JavaScript.
                    } else {
                        statusMessage.textContent = "Please select a file to upload.";
                    }
                });
            });
        </script>

        <div id="or">
            OR...You can <a id="showButton" href="#alternative">answer the following questions</a>
        </div>


        <div id="alternative-outer-container">
            <div id="alternative" class="transparentContainerBox" style="display: none;">
                <div id="alternative-inner-container">
                    <p class="second-title">Please answer the following questions:</p>
                    <div>
                        <div id="question-1-Education">
                            <h3>1.Education</h3>
                            <form>
                                <div>
                                    <label for="highest-level-education" class="questions-setup-text">Highest Level of
                                        Education:</label>
                                    <select name="highest-level-education" id="highest-level-education" required="">
                                        <option value="" disabled selected>Select an option</option>
                                        <option value="1">High school or equivalent</option>
                                        <option value="2">Associate degree</option>
                                        <option value="3">Bachelor's degree</option>
                                        <option value="4">Master's degree</option>
                                        <option value="5">Doctorate</option>
                                    </select>
                                </div>

                                <div>
                                    <label for="major">Major:</label>
                                    <input type="text" id="major" name="major" required maxlength="50">
                                </div>

                                <div>
                                    <label for="other-education">Other education or training you had:<br></label>
                                    <input type="text" id="other-education" name="other-education" maxlength="100">
                                </div>

                            </form>
                        </div>

                        <div id="question-2-WorkExperience">
                            <h3>2.Work Experience</h3>
                            <form>
                                <div>
                                    <label for="years-of-experience" class="questions-setup-text">Years of
                                        Experience:</label>
                                    <select name="years-of-experience" id="years-of-experience" required="">
                                        <option value="" disabled selected>Select an option</option>
                                        <option value="1">0-1 year</option>
                                        <option value="2">1-3 years</option>
                                        <option value="3">3-5 years</option>
                                        <option value="4">5-10 years</option>
                                        <option value="5">10+ years</option>
                                    </select>
                                </div>

                                <div>
                                    <label for="industry">Industry:</label>
                                    <input type="text" id="industry" name="industry" maxlength="50">
                                </div>

                                <div>
                                    <label for="position">Position:</label>
                                    <input type="text" id="position" name="position" maxlength="50">
                                </div>

                                <div>
                                    <label for="duty">Duty:<br></label>
                                    <input type="text" id="duty" name="duty" maxlength="300">
                                </div>

                                <div>
                                    <label for="other-work">Other work experience you had:<br></label>
                                    <input type="text" id="other-work" name="other-work" maxlength="300">
                                </div>
                            </form>
                        </div>

                        <div id="question-3-skills">
                            <h3>3.Skills</h3>
                            <form>
                                <div>
                                    <label for="skills">Tell us about any skills you mastered or any certificate you
                                        earned,
                                        technical skills are preferred:<br></label>
                                    <input type="text" id="skills" name="skills" maxlength="200">
                                </div>
                            </form>
                        </div>
                        <a href="{% url 'interview:career_interests' %}"
                           id="next-button-two" class="submit-button">Next<i class="fa-regular fa-circle-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script>
        // Get a reference to the button and the hidden section
        const showButton = document.getElementById("showButton");
        const hiddenSection = document.getElementById("alternative");

        // Add a click event listener to the button
        showButton.addEventListener("click", function () {
            // Toggle the visibility of the hidden section
            hiddenSection.style.display = "block"; // Show the hidden section
        });
    </script>

</main>

{% endblock %}

v1/interview/templates/interview/career-builder-interests.html
{% extends 'interview/nav.html' %}

{% block header %}
<head>
    {% load static %}
    <meta charset="utf-8">
    <title>Career Path Builder - Interests</title>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link rel="stylesheet" type="text/css" href="{% static 'interview/css/career-builder-interests.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'interview/css/nav.css' %}">
    <style>
        body {
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
        }
    </style>
    <script src="https://kit.fontawesome.com/1a12d6fc49.js" crossorigin="anonymous"></script>
</head>
{% endblock %}

{% block content %}

<main>
    <section id="sideNavContainer">
        <p id="sidemenu-background"><i class="fa-regular fa-circle-check" id="first-icon"></i>Background</p>
        <p id="sidemenu-interests"><i class="fa-regular fa-circle-check" id="second-icon"></i>Interests</p>
        <p id="sidemenu-preferences"><i class="fa-regular fa-circle-check" id="third-icon"></i>Preferences</p>
        <p id="sidemenu-personality"><i class="fa-regular fa-circle-check" id="forth-icon"></i>Personality</p>
    </section>

    <section id="mainContent">
        <div id="tell-us-about-yourself-container">
            <div class="theBrownVerticalDecoBar">
                <div id="tell-us-about-yourself">Tell us about yourself, we will gather your information and provide
                    career track recommendations based on your answer.
                </div>
            </div>
        </div>

        <div id="select-interests" class="transparentContainerBox">
            <div id="select-interests-inner-container">
                <h1 id="title-interests">Interests</h1>
                <p>Select five at most:</p>
                <div id="nine-options-container">
                    <div id="nine-options">
                        <div class="one-lane">
                            <button class="option-button">Big Tech</button>
                            <button class="option-button">Consumer Brand</button>
                            <button class="option-button">Environment</button>
                        </div>
                        <div class="one-lane">
                            <button class="option-button">Startup</button>
                            <button class="option-button">Consulting</button>
                            <button class="option-button">Politics</button>
                        </div>
                        <div class="one-lane">
                            <button class="option-button">Investment</button>
                            <button class="option-button">Arts</button>
                            <button class="option-button">Healthcare</button>
                        </div>
                        <div class="one-lane">
                            <button class="option-button">AI</button>
                            <button class="option-button">Education</button>
                            <button class="option-button">Social Work</button>
                        </div>
                    </div>
                </div>
                <div id="form">
                    <label for="other-interests">What you are interested are not listed? You can type it
                        here:<br></label>
                    <input type="text" id="other-interests" name="other-interests" maxlength="200">
                </div>

            </div>
            <script>
                // Get a collection of elements with the class "option-button"
                const buttons = document.getElementsByClassName("option-button");

                // Loop through each button and add a click event listener
                for (let i = 0; i < buttons.length; i++) {
                    buttons[i].addEventListener("click", function () {
                        // Add a class to change the style after it's clicked
                        this.classList.add("clicked");
                        this.disabled = true;
                    });
                }
            </script>

        </div>
        <div id="next-button-container">
            <a href="{% url 'interview:career_preferences' %}" id="next-button-two" class="submit-button">Next<i
                    class="fa-regular fa-circle-right"></i></a>
        </div>
    </section>


</main>

{% endblock %}

v1/interview/templates/interview/messages.html
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
      {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="True">&times;</span>
    </button>
  </div>
</div>
{% endfor %}

v1/interview/templates/interview/nav.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

{% block header %}
{% endblock %}

<body>
<nav>
    <div id="navContainer">
        <img src="{% static 'interview/images/Logo.svg' %}" alt="Company Logo" id="companyLogo"/>
        <ul id="navBar">
            <li class="navMenu"><a href="{% url 'interview:landing_page' %}" class="nav-menu-color">Home</a></li>
            <li class="navMenu"><a href="{% url 'interview:landing_page' %}" class="nav-menu-color">Mock Interview</a></li>
            {#--summary临时用--#}
            <li class="navMenu"><a href="{% url 'interview:dashboard_main' %}" class="nav-menu-color">Dashboard</a></li>
            {#--summary临时用--#}
            <li class="navMenu"><a href="{% url 'interview:career_intro' %}" class="nav-menu-color">Career Path Builder</a></li>
            <li class="navMenu"><a href="{% url 'interview:track_intro' %}" class="nav-menu-color">Smart Tracking</a></li>
            {% if user.is_authenticated %}
	            <li class="navMenu"><a href="{% url 'interview:logout' %}" class="nav-menu-color" id="logoutButton">Logout</a></li>
            {% else %}
                <li class="navMenu"><a href="{% url 'interview:login' %}" id="loginButton">Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

{% block content %}
{% endblock %}

</body>
</html>

v1/interview/templates/interview/setup_page.html
{% extends 'interview/nav.html' %}

{% block header %}

<head>
    {% load static %}
    <meta charset="utf-8">
    <title>Customize Your Interview</title>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link rel="stylesheet" type="text/css" href="{% static 'interview/css/interviewsetup.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'interview/css/nav.css' %}">
    <style>
        body {
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
        }
    </style>
</head>
{% endblock %}

{% block content %}

<main>

    <section class="section-wrapper">
        <div id="question-list" class="container">
            <h3>Select a Question List to Start Practice!</h3>
            <div id="container-wrapper">
                <div class="container">
                    <div class="inner-container">
                        <a href="{% url 'interview:hint_page' 'top10' %}" class="list-button" id="behavioral">
                            <div class="list">
                                <div class="list-title">Top 10 Behavioral Questions</div>
                                <img class="list-pic" src="{% static 'interview/images/behavior.png' %}"
                                    alt="human behavior" />
                            </div>
                        </a>
                    </div>
                </div>
                <div class="container">
                    <a href="{% url 'interview:hint_page' 'teamwork' %}" class="list-button" id="teamwork">
                        <div class="list">
                            <div class="list-title">Teamwork<br> Questions</div>
                            <img class="list-pic" src="{% static 'interview/images/teamwork.png' %}"
                                alt="4 hands holding on to each other, showing seamless colaboration" />
                        </div>
                    </a>
                    <a href="{% url 'interview:hint_page' 'communication' %}" class="list-button" id="communication">
                        <div class="list">
                            <div class="list-title">Communication Questions</div>
                            <img class="list-pic" src="{% static 'interview/images/chat.png' %}" alt="3 chat boxes" />
                        </div>
                    </a>
                </div>
                <div class="container">
                    <a href="{% url 'interview:hint_page' 'leadership' %}" class="list-button" id="leadership">
                        <div class="list">
                            <div class="list-title">Leadership<br> Questions</div>
                            <img class="list-pic" src="{% static 'interview/images/leadership.png' %}" alt="leader" />
                        </div>
                    </a>
                    <a href="{% url 'interview:hint_page' 'decision_making' %}" class="list-button" id="decision">
                        <div class="list">
                            <div class="list-title">Decision-making Questions</div>
                            <img class="list-pic" src="{% static 'interview/images/teaching.png' %}"
                                alt="One person presenting in front of a chart" />
                        </div>
                    </a>

                </div>
            </div>
        </div>

        <div id="or" class="container">
            <p>OR</p>
        </div>

        <div id="question-based-on-resume" class="container">
            <h3>Generate Interview Questions Based on Your Resume</h3>
            <button class="submit-button" id="upload-resume">Upload Resume</button>
            <img id="drag-to-upload" src="{% static 'interview/images/drag.png' %}" /></div>
    </section>


    <section id="start-button-container">
        <button class="submit-button" id="start">Start Now</button>
    </section>
    </div>
</main>


<!-- <main>
    
        <div class="transparentContainerBox">
            <div id="setupBox" class="content-section">
            <div id="setupQuestion">
                <div class="theBrownVerticalDecoBar">
                    <p>Tell us more about yourself and customize your mock interview experience</p>
                </div> -->

<!--Setup Form-->
<!-- <div class="form-block w-form">
                    <form id="wf-form-interview-setup-Form" name="wf-form-interview-setup-Form"
                          data-name="interview setup Form" method="post" class="interview-setup-form"
                          data-wf-page-id="644dd40e1a62013c9d0dab85"
                          data-wf-element-id="bde9699f-01e1-5fbf-8f15-b8c9853ce5ac"
                          action="{% url 'interview:setup_page' %}">
                        {% csrf_token %} -->

<!--Select Role-->
<!-- <div class="div-block-2">
                            <label for="YOE" class="questions-setup-text">Choose Your Role:</label>
                            <label class="radio-button-field w-radio">
                                <input type="radio" id="individual-contributor" name="role"
                                       value="individual-contributor" required=""
                                       class="w-form-formradioinput w-radio-input"
                                       checked>
                                <span class="radio-button-label w-form-label" for="individual-contributor">Individual Contributor</span>
                            </label>
                            <label class="w-radio">
                                <input type="radio" id="manager" name="role" value="manager"
                                       class="w-form-formradioinput w-radio-input">
                                <span class="radio-button-label w-form-label" for="manager">Manager</span>
                            </label>
                        </div>
 -->

<!--Select years of experience-->
<!-- <div class="div-block-2">
                            <label for="YOE" class="questions-setup-text">Years of Experience:</label>
                            <select class="w-select" name="YOE" id="YOE" required="">
                                <option value="" disabled selected>Select an option</option>
                                <option value="1">0-1 year</option>
                                <option value="2">1-3 years</option>
                                <option value="3">3-5 years</option>
                                <option value="4">5-10 years</option>
                                <option value="5">10+ years</option>
                            </select>
                        </div> -->

<!--Select # of Questions-->
<!-- <div class="div-block-2">
                            <label for="YOE-4" class="questions-setup-text">Number of Questions:</label>
                            <label class="radio-button-field w-radio">
                                <input type="radio" data-name="Radio 3" id="radio-3" name="n_question" value="3"
                                       class="w-form-formradioinput w-radio-input" checked>
                                <span class="w-form-label" for="radio-3">  3    </span></label>
                            <label class="w-radio">
                                <input type="radio" data-name="Radio 3" id="radio-3" name="n_question" value="5"
                                       class="w-form-formradioinput w-radio-input">
                                <span class="radio-button-label w-form-label" for="radio-3">  5    </span></label>
                            <label class="radio-button-field-2 w-radio">
                                <input type="radio" data-name="Radio 5" id="radio-5" name="n_question" value="7"
                                       class="w-form-formradioinput w-radio-input">
                                <span class="radio-button-label w-form-label" for="radio-5">  7    </span>
                            </label>
                        </div> -->

<!--Start Button-->
<!-- <div class="div-block-3">
                            <input type="submit" value="Start Now" class="submit-button">
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </div>

</main> -->


{% endblock %}